$NetBSD: patch-config_elasticsearch.yml,v 1.6 2017/11/20 15:36:47 fhajny Exp $

Define various paths

--- config/elasticsearch.yml.orig	2017-11-10 18:40:01.000000000 +0000
+++ config/elasticsearch.yml
@@ -31,10 +31,12 @@
 # Path to directory where to store the data (separate multiple locations by comma):
 #
 #path.data: /path/to/data
+path.data: @ES_DBDIR@
 #
 # Path to log files:
 #
 #path.logs: /path/to/logs
+path.logs: @ES_LOGDIR@
 #
 # ----------------------------------- Memory -----------------------------------
 #
